channels:
  - conda-forge
  - anaconda
dependencies:
  - elasticsearch=8
  - fastapi
  - loguru
  - pydantic
  - python-multipart
  - uvicorn[standard]
  - pip:
    - langchain==0.1.3
    - langchain-community==0.0.15
    - langchain-openai==0.0.3
    - tiktoken==0.5.2