channels:
  - conda-forge
  - anaconda
dependencies:
  - elasticsearch=8
  - fastapi
  - loguru
  - pydantic
  - python-multipart
  - uvicorn[standard]
  - pip:
    - langchain>=0.2.5
    - langchain-community
    - langchain-openai>=0.1.8
    - langchain-elasticsearch
    - tiktoken